# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPred <- function(C, X) {
    .Call(`_andsr_getPred`, C, X)
}

getRMSE <- function(v1, v2) {
    .Call(`_andsr_getRMSE`, v1, v2)
}

getMAE <- function(v1, v2) {
    .Call(`_andsr_getMAE`, v1, v2)
}

getRho <- function(v1, v2) {
    .Call(`_andsr_getRho`, v1, v2)
}

getNEDist <- function(X) {
    .Call(`_andsr_getNEDist`, X)
}

getGeodesDist <- function(dmat, k) {
    .Call(`_andsr_getGeodesDist`, dmat, k)
}
getLMDist <- function(X, theta) {
    .Call(`_andsr_getLMDist`, X, theta)
}

getOptHT <- function(sv, m, n) {
    .Call(`_andsr_getOptHT`, sv, m, n)
}

smapSVD <- function(X, y, wmat) {
    .Call(`_andsr_smapSVD`, X, y, wmat)
}

smapRidge <- function(X, y, wmat, lambda) {
    .Call(`_andsr_smapRidge`, X, y, wmat, lambda)
}

lmdSmplx <- function(X, y, dmat, idxLib, idxPrd, nns) {
    .Call(`_andsr_lmdSmplx`, X, y, dmat, idxLib, idxPrd, nns)
}

lmdSMap <- function(X, y, idxLib, idxPrd, method, theta, lambda) {
    .Call(`_andsr_lmdSMap`, X, y, idxLib, idxPrd, method, theta, lambda)
}

funcTPSA <- function(gSeed, threadNo, iterLim, tsLength, criterion, method, diag, sigmas, temps, X, y, idxLib, idxPrd) {
    .Call(`_andsr_funcTPSA`, gSeed, threadNo, iterLim, tsLength, criterion, method, diag, sigmas, temps, X, y, idxLib, idxPrd)
}

